### ISSUE TITLE
Refactoring Meta/Roadmap

### ISSUE THREAD

**Issue by 0robustus1** [ontohub/ontohub#839]
This is a Milestone meta issue for the [**Refactoring after FOIS**](https://github.com/ontohub/ontohub/issues?milestone=15&state=open) milestone.

It shall serve as some sort of roadmap:
1. [x] Fixing whitespace issues across the project (see #840)
   - This includes _trailing whitespace_ and _tabs_
     in `.rb`, `.css.sass`, `.js` and `.js.coffee` files.
2. [x] Renaming code in order to use same semantics, see #455.
   - Affects **variable names**, **constant names**, **model names**, **fields**, **tables**, **method names**.
3. [ ] Tackle other issues of the milestone.
